apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: descomplicandok8s
  region: us-east-2
  version: "1.35"

iam:
  withOIDC: true

managedNodeGroups:
  - name: ng-descomplicandok8s
    instanceType: t3.medium
    minSize: 1
    maxSize: 3
    desiredCapacity: 1

    # --- OTIMIZAÇÃO DE DISCO ---
    volumeSize: 20
    volumeType: gp3       # <--- MAIS BARATO: gp3 custa $0.08/GB vs $0.10/GB do gp2
    volumeIOPS: 3000      # Grátis no gp3 (incluso no preço base)
    volumeThroughput: 125 # Grátis no gp3 (incluso no preço base)

    tags:
      NodeType: on-demand
      env: descomplicandok8s
      ami-family: ec2-linux


addons:
  - name: vpc-cni
    version: latest
    attachPolicyARNs:
      - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
  - name: coredns
    version: latest
  - name: kube-proxy
    version: latest